### PR TITLE
Issue 718 - Fix bounding box issue on image redactor 

### PR DESCRIPTION
**Pull request by rakan41**
## Change Description

Image redactor occasionally creates an extra bounding box for the word following the PII text. This occurs when the PII text consists of more than one word and the preceding word is longer than the following word. This is caused by the bounding box location incrementing by the length of the following word, rather than length of the current. 

This fixes the above issue by ensuring the bounding box location increments by the current word's length. 

# Unit Test 
**Original Image**
image
**Redaction before code change**
image
**Redaction after code change**
image

## Issue reference

This PR fixes issue #718 

## Checklist
- [ X] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [ X] I have signed the CLA
- [ X] My code includes unit tests
- [ X] All unit tests and lint checks pass locally
- [ X] My PR contains documentation updates / additions if required

### CODE REVIEW

**Comment by omri374** [comment]
Thanks @rakan41!

**Comment by omri374** [comment]
There is a failing e2e test:

```py
image_analyzer_engine = <presidio_image_redactor.image_analyzer_engine.ImageAnalyzerEngine object at 0x7f621a196070>

    def test_given_image_then_text_entities_are_recognized_correctly(image_analyzer_engine):
        # Image with PII entities
        image = get_resource_image("ocr_test.png")
        analyzer_results = image_analyzer_engine.analyze(image)
        assert len(analyzer_results) == 7
        results = __get_expected_ocr_test_image_analysis_results()
        for i in range(7):
>           assert analyzer_results[i] == results[i]
E           assert type: EMAIL_ADDRESS, start: 773, end: 795, score: 1.0 == type: EMAIL_ADDRESS, start: 772, end: 794, score: 1.0

tests/integration/test_image_analyzer_engine_integration.py:12: AssertionError
=========================== short test summary info ============================
FAILED tests/integration/test_image_analyzer_engine_integration.py::test_given_image_then_text_entities_are_recognized_correctly
```

**Comment by omri374** [comment]
Hi @rakan41, in addition to unit tests on the analyzer module, there are e2e tests which validate the APIs and integrations between modules. E2E tests can be found here: https://github.com/microsoft/presidio/tree/main/e2e-tests
Please reach out here or through presidio@microsoft.com if you need any help setting up these tests. Thanks!

**Comment by omri374** [comment]
Hi @rakan41, can we help with this in any way?

**Comment by rakan41** [comment]
> Hi @rakan41, can we help with this in any way?

Apologies, it's been a bit crazy lately. Will definitely try to look at this sometime next week!

**Comment by rakan41** [comment]
Hi @omri374 , 
It looks like it now passes the AZP checks. Please let me know if there are any actions on my part before approving PR. 
Cheers,

**Comment by omri374** [comment]
Would it be possible to add a test for this?

**Comment by rakan41** [comment]
> 
> 
> Would it be possible to add a test for this?

Hi @omri374 , sure no problem. Could I get some guidance please? Do I merely add a test function in the "test_image_redactor_engine.py" file? 
If so, would a test based the unit test I made above be sufficient? 
Thanks,

**Comment by omri374** [comment]
I think a test could be your before and after images (as an integration test).

**Comment by omri374** [comment]
Hi @rakan41, maybe this can help?
```python
@pytest.mark.parametrize(
    "input_image_file, redacted_image_file ,fill_color",
    [
        ("ocr_test.png", "ocr_test_redacted_matrix.png", (255, 0, 0)),
        ("img2.png", "img2_redacted.png", (255, 192, 203)),
    ],
)
def test_given_image_with_text_and_matrix_fill_then_text_is_colored_out(
    input_image_file, redacted_image_file, fill_color
):
    # Image with PII entities
    image = get_resource_image(input_image_file)

    redacted_image = ImageRedactorEngine().redact(image, fill_color)
    expected_result_image = get_resource_image(redacted_image_file)
    assert compare_images(redacted_image, expected_result_image)
    assert not compare_images(redacted_image, image)

```

Which extends the test `test_given_image_with_text_and_matrix_fill_then_text_is_colored_out` to be parameterized and also checks for the use case in this PR. The files `img2.png` and `img2_redacted.png` are the example files you added to this PR.

**Comment by rakan41** [comment]
> 
> 
> Hi @rakan41, maybe this can help?
> 
> ```python
> @pytest.mark.parametrize(
>     "input_image_file, redacted_image_file ,fill_color",
>     [
>         ("ocr_test.png", "ocr_test_redacted_matrix.png", (255, 0, 0)),
>         ("img2.png", "img2_redacted.png", (255, 192, 203)),
>     ],
> )
> def test_given_image_with_text_and_matrix_fill_then_text_is_colored_out(
>     input_image_file, redacted_image_file, fill_color
> ):
>     # Image with PII entities
>     image = get_resource_image(input_image_file)
> 
>     redacted_image = ImageRedactorEngine().redact(image, fill_color)
>     expected_result_image = get_resource_image(redacted_image_file)
>     assert compare_images(redacted_image, expected_result_image)
>     assert not compare_images(redacted_image, image)
> ```
> 
> Which extends the test `test_given_image_with_text_and_matrix_fill_then_text_is_colored_out` to be parameterized and also check for the use case in this PR. The files `img2.png` and `img2_redacted.png` are the example files you added to this PR.

This looks helpful! I'll try incorporate something like this.

**Comment by rakan41** [comment]
Added image resource to testing folder. Also added unit which checks that redacting that image matches the pre-redacted image (as seen in trail above)

**Review by omri374 — APPROVED** [review]

**Review by SharonHart — DISMISSED** [review]
LGTM!
You have conflicts with your previous change 😄

**Comment by rakan41** [comment]
> 
> 
> LGTM!
> You have conflicts with your previous change 😄

@SharonHart , I've resolved conflict. I've included both test functions, as one relates to Issue 718 and the other to Issue 749. Hope it is all good now :)

**Review by SharonHart — APPROVED** [review]

**Review by omri374 — APPROVED** [review]

**Pull request merged**
