### PR TITLE
Add Dockerfile for Windows containers

### PR DESCRIPTION
**Pull request by TheIndra55**
## Change Description

Adds a Dockerfile for building the containers for Windows containers.

Allows running the images natively on Windows. Tested the image build and run on Windows 11 22H2.

## Checklist

- [x] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [x] I have signed the CLA (if required)
- [ ] My code includes unit tests
- [ ] All unit tests and lint checks pass locally
- [ ] My PR contains documentation updates / additions if required

### CODE REVIEW

**Comment by TheIndra55** [comment]
@microsoft-github-policy-service agree company="BusinessMonitor"

**Comment by omri374** [comment]
Thanks!

**Comment by omri374** [comment]
Hi @TheIndra55, apologies for the late reviews. We'd like to test this, hence the delay.

**Comment by TheIndra55** [comment]
No problem, we have our own fork. Please let me know you have any comments 🙂

**Review by omri374 — APPROVED** [review]

**Review by SharonHart — APPROVED** [review]

**Pull request merged**
