### PR TITLE
Anonymize txt image updates

### PR DESCRIPTION
**Pull request by tpb1962**
## Change Description
Changes to add clarity when using anonymize text and image.  The issue references Windows 10 but these changes for setup with Docker and testing of Presidio anonymize text and image on any platform. Hopefully helpful for those with limited python and docker experience. 

Changes to:
deploy.md
samples.md
build.sh
run.sh

This is my first pull request. Apologies in advance for any errors.

## Issue reference
#359 Run on Windows 10

## Checklist
- [ X] I have reviewed the [contribution guidelines](../../CONTRIBUTING.md)
- [x] I have signed the CLA
- [ ] My code includes unit tests
- [X ] All unit tests and lint checks pass locally
- [X ] My PR contains documentation updates / additions if required
- [X ] My code doesn't require a change in the project's Protobuf definition (github.com/microsoft/presidio-genproto) or if they do, I have submitted a PR for a protobuf change. Link to presidio-genproto PR:

### CODE REVIEW

**Comment by omri374** [comment]
Hi @tpb1952, Thanks for the PR! Great additions!

A suggestion: Instead of adding the analyze-image and anonymize-image to the standard build/deploy scripts, how about we create additional ones? Most users are interested in only the text part and this would increase the complexity of build/deploy.

**Comment by tpb1962** [comment]
> Hi @tpb1962, Thanks for the PR! Great additions!
> 
> A suggestion: Instead of adding the analyze-image and anonymize-image to the standard build/deploy scripts, how about we create additional ones? Most users are interested in only the text part and this would increase the complexity of build/deploy.

Hi @omri374 - I agree. Separate scripts would be the best way to go.

**Comment by omri374** [comment]
@tpb1962 Would you prefer updating this PR with the two build.sh files? Or create a PR with docs only for now?

**Comment by tpb1962** [comment]
> @tpb1962 Would you prefer updating this PR with the two build.sh files? Or create a PR with docs only for now?

Hi @omri374 . I think I with create a PR for just docs only. I need to review and update as I think I can state better some of the things I had in original PR docs. Thanks!

**Comment by omri374** [comment]
Hi #tpb1962, still interested in doing this PR?

**Comment by tpb1962** [comment]
Hi @omri374 . Closing this PR and will do a new onw of updating documentation only.

Thanks!

**Comment by omri374** [comment]
Thanks @tpb1962!

**Pull request closed without merging**
