### PR TITLE
Analyzer and Anonymizer deps bump

### PR DESCRIPTION
**Pull request by omri374**
## Change Description
Updates to Pipfile and setup.py for analyzer and anonymizer

### CODE REVIEW

**Review by SharonHart — DISMISSED** [review]

**Review by navalev — APPROVED** [review]

**Comment by omri374** [comment]
@navalev @SharonHart after doing this I was thinking, maybe we shouldn't limit the deps versions to the maximum? We know it's working on lower versions. WDYT would be the best approach here?
For example, we had spacy version 3.0.6 first and now it's tested on 3.1.x. Maybe we should specify the version to be `spacy>=3.0.6`?

**Comment by SharonHart** [comment]
@omri374 In our case, maybe locking to minor version is the best, since we saw how text, and specifically the demo one, tend to recognized differently with each version of spacy. Other packages might be more relaxed-versioned

**Comment by omri374** [comment]
@SharonHart how about `spacy >=3.0.6, <=3.3`?
It works on 3.2

**Comment by SharonHart** [comment]
@omri374 Missing lock file for image-redactor?

**Comment by omri374** [comment]
@SharonHart yes please ignore for now. I can't seem to lock and make it work on all python versions. Will keep on trying

**Comment by SharonHart** [comment]
I'll try myself tomorrow as well

**Review by SharonHart — APPROVED** [review]

**Review by navalev — APPROVED** [review]

**Comment by omri374** [comment]
Closing for now to introduce some updates

**Pull request closed without merging**
