### PR TITLE
Add Italian passport and identity card recognizers

### PR DESCRIPTION
**Pull request by darella**
## Italian passport and identity card recognizers

This contribution adds two recognizers for Italian language using pattern matching and context words:

- Passport number
- Identity card number

## Issue reference

This PR fixes issue #929

## Checklist

- [x] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [x] I have signed the CLA
- [x] My code includes unit tests
- [x] All unit tests and lint checks pass locally
- [x] My PR contains documentation updates / additions if required

### CODE REVIEW

**Comment by darella** [comment]
> 

@microsoft-github-policy-service agree [company="{PagoPA S.p.A.}"]

**Comment by darella** [comment]
@microsoft-github-policy-service agree company="PagoPA S.p.A."

**Comment by darella** [comment]
> @microsoft-github-policy-service agree company="PagoPA S.p.A."

**Review by omri374 — APPROVED** [review]
LGTM, thanks!

**Review by SharonHart — APPROVED** [review]

**Pull request merged**
