### PR TITLE
Fix spacy_stanza.md example

### PR DESCRIPTION
**Pull request by ksjogo**
## Change Description

The example was missing the super call in the constructor. Thus the example will fail as the super constructor initialized the ner config.

## Issue reference

This PR fixes issue #XX

## Checklist

- [ ] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [ ] I have signed the CLA (if required)
- [ ] My code includes unit tests
- [ ] All unit tests and lint checks pass locally
- [X] My PR contains documentation updates / additions if required

### CODE REVIEW

**Comment by omri374** [comment]
Hi, I'm not sure that passing the loaded spacy model into the parent class init is the right way to go.
Looking at the init for `SpacyNlpEngine`, it accepts a models dict and an ner_model_configuration
https://github.com/microsoft/presidio/blob/a6e253d0e7846c761144aa172844ddd6016a3970/presidio-analyzer/presidio_analyzer/nlp_engine/spacy_nlp_engine.py#L29

The models are already loaded, so no need to pass them. If a user requires a different `NerModelConfiguration`, then this should be passed to the super.

**Comment by omri374** [comment]
Closing, please re-open if you'd like to continue working on this.

**Comment by ksjogo** [comment]
@omri374 don't have rights to re-open PRs in this repo.
Did remove the argument in my origin branch. But I think it is not updating closed MRs.

**Comment by omri374** [comment]
Reopened

**Pull request merged**
