### PR TITLE
Added py.typed file and modified the setup.py files

### PR DESCRIPTION
**Pull request by Ashhar-24**
## Change Description

As the issue #905 wanted to add missing `py.typed` in published packages in order to support `mypy/pyright` type checking, I've added `py.typed` files in all the three libraries `presidio-analyzer` , `presidio-anonymizer` and `presidio-image-redactor`.

## Issue reference

This PR fixes issue #905 

## Checklist

- [ ] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [ ] I have signed the CLA (if required)
- [ ] My code includes unit tests
- [ ] All unit tests and lint checks pass locally
- [ ] My PR contains documentation updates / additions if required

### CODE REVIEW

**Comment by Ashhar-24** [comment]
@microsoft-github-policy-service agree

**Comment by Ashhar-24** [comment]
Do I need to make any changes @omri374 in the code?

**Comment by omri374** [comment]
Hi @Ashhar-24, thanks for this! I don't think so, but we'll check internally. I ran mypy after this change and there are a few issues that it raised. We'll discuss it internally and get back to you. The CI is failing due to a different problem, sorry about that.

**Review by omri374 — APPROVED** [review]

**Comment by Ashhar-24** [comment]
@omri374 can you please add a `hacktoberfest-accepted` label so that this PR gets counted as a `successful-PR` for me in the `hacktoberfest` programm.

**Comment by Ashhar-24** [comment]
@omri374 one last thing, how much time will it take to get this PR merged, like in order to merge this PR requires `At least 2 approving reviews `.

**Review by omri374 — APPROVED** [review]

**Pull request merged**
