### PR TITLE
Added Indian PII recognizers

### PR DESCRIPTION
**Pull request by Nilanjan96**
Added Indian Aadhar Card, PAN Card, Driving License Number, Passport, Voter Card, Phone Number recognizers

### CODE REVIEW

**Comment by omri374** [comment]
Hi @Nilanjan96, thanks for your contribution!

A few initial comments:
1. Have you ran any verification on these recognizers to see their precision/recall values? If any of these have unusually high false positives or false negative values? A combination of ambiguous regex (e.g. in the extreme case, a regex checking that there are 5 to 7 digits) and ambiguous context values (e.g. "number","card") are likely to introduce many false positives.
2. I think it would be best to put all the new recognizers in predefined_recognizers/india or something like that, as we are starting to have a large number of recognizers.
3. Could you verify if any of these have an ability to add checksum/other forms of validation? This could really help to increase the confidence of identification.

**Comment by omri374** [comment]
Also, please run pytest, flake and pylint, as there are some syntax errors. See reference here: https://github.com/microsoft/presidio/blob/master/docs/development.md#dev-python

**Comment by Nilanjan96** [comment]
Sure thing. I am sorry for being late. I will look into this now.

**Comment by Nilanjan96** [comment]
As for the part 1, I did run this test on several hundreds of fake PII data. I did have some problems because US DRIVER LICENSE was marking every 14 letter word as US DRIVER LICENSE as well as a lot of other stuff. I will check the common words like "card" and "number".

**Comment by omri374** [comment]
US_DRIVER_LICENSE is a weak regex, but it usually emits confidence = 0.01. A threshold on confidence would ignore these findings

**Comment by omri374** [comment]
Closing as there's no response from the author

**Pull request closed without merging**
