### PR TITLE
Changes to Anonymizer packages/imports + added repr to classes.

### PR DESCRIPTION
**Pull request by omri374**
## Change Description

1. Refactored the Presidio Anonymizer package structure for simpler use. For example, instead of
`from presidio_anonymizer.entities.engine.operator_config import OperatorConfig` 
use 
`from presidio_anonymizer.entities import OperatorConfig` among others.

2. Updated the anonymizer documentation
3. Black code formatting
4. Added `__repr__` to classes for better developer experience in interactive settings.

> Note: this PR turned out to be long but most of the changes are related to changes in imports + black formatting changes across the entire anonymizer package.

## Issue reference

This PR fixes issue #753

## Checklist

- [X] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [X] I have signed the CLA
- [X] My code includes unit tests
- [X] All unit tests and lint checks pass locally
- [X] My PR contains documentation updates / additions if required

### CODE REVIEW

**Comment by omri374** [comment]
@navalev docs tests are failing due to a mismatch between pypi version and this proposed version. Should we consider using the local version when testing docs?

**Comment by navalev** [comment]
> @navalev docs tests are failing due to a mismatch between pypi version and this proposed version. Should we consider using the local version when testing docs?

the docs test pipeline should be revisited, it works against the published version, hence failing on major changes. I will handle this in a seperate PR.

**Review by navalev — APPROVED** [review]
looks good. majority of tests , as mentioned, are docs, samples and tests.

**Review by SharonHart — APPROVED** [review]
Looks great!

**Pull request merged**
