### PR TITLE
Add 50-60 number range to itin recognizer

### PR DESCRIPTION
**Pull request by aperezfals**
## Change Description

Add the range of numbers from 50 to 65 to the patterns of `us_itin_recognizer`. Clean the regexes

## Issue reference
https://github.com/microsoft/presidio/issues/954
This PR fixes issue #954

## Checklist

- [ ] Add the range from 50 to 65 to the middle part of an itin in all regexes
- [ ] Eliminate unnecessary groups in the regexes
- [ ] Eliminate unnecessary quantifiers from the regexes
- [ ] Add positive tests cases for the range from 50 to 65

### CODE REVIEW

**Comment by aperezfals** [comment]
@microsoft-github-policy-service agree

**Review by aflores-qb — APPROVED** [review]
LGTM, a lot easier to read

**Review by omri374 — APPROVED** [review]
Thanks! great contribution.

**Review by SharonHart — APPROVED** [review]

**Pull request merged**
