### PR TITLE
Improve url detector

### PR DESCRIPTION
**Pull request by afogel**
## Change Description

Currently, the presidio URL detector does not appropriately recognize URLs from less common, albeit valid, gTLDs. For example, if attempting to recognize the URL of https://webhook.site/a8eedfd6-9d8a-44e0-b0fc-cc7d517db5dc?q=1&b=2, the recognizer will only match on `https://webhook.si`, thus missing the complete URL including query params.
This change fixes it.

The list of URLs was pulled from the list of gTLDs supported by namecheap as of today:
https://www.namecheap.com/domains/full-tld-list/ 

## Issue reference

There was no related issue opened, this was simply uncovered through the use of presidio analyzers.

## Checklist

- [X] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [X] My code includes unit tests
- [X] All unit tests and lint checks pass locally
- [X] My PR contains documentation updates / additions if required

### CODE REVIEW

**Comment by afogel** [comment]
@microsoft-github-policy-service agree [company="Pillar Security"]

**Comment by afogel** [comment]
@microsoft-github-policy-service agree company="Pillar Security"

**Review by omri374 — APPROVED** [review]
Thanks!

**Pull request merged**
