### PR TITLE
Do not count on the order of the list when testing

### PR DESCRIPTION
**Pull request by shiranr**
Fix test

### CODE REVIEW

**Comment by navalev** [comment]
this does not seem to resolve the issue with this test. When running with tesseract 4.0 there are different results for the image analyzer:
assert type: EMAIL_ADDRESS, start: 773, end: 795, score: 1.0 in [type: PERSON, start: 31, end: 44, score: 0.85, type: PERSON, start: 31, end: 44, score: 0.85, type: DOMAIN_NAME, star... 0.7, type: PHONE_NUMBER, start: 332, end: 346, score: 0.7, type: EMAIL_ADDRESS, start: 772, end: 794, score: 1.0, ...]

**Review by navalev — CHANGES_REQUESTED** [review]
this does not seem to resolve the issue with this test. When running with tesseract 4.0 there are different results for the image analyzer:
assert type: EMAIL_ADDRESS, start: 773, end: 795, score: 1.0 in [type: PERSON, start: 31, end: 44, score: 0.85, type: PERSON, start: 31, end: 44, score: 0.85, type: DOMAIN_NAME, star... 0.7, type: PHONE_NUMBER, start: 332, end: 346, score: 0.7, type: EMAIL_ADDRESS, start: 772, end: 794, score: 1.0, ...]

**Review by omri374 — APPROVED** [review]

**Comment by shiranr** [comment]
> this does not seem to resolve the issue with this test. When running with tesseract 4.0 there are different results for the image analyzer:
> assert type: EMAIL_ADDRESS, start: 773, end: 795, score: 1.0 in [type: PERSON, start: 31, end: 44, score: 0.85, type: PERSON, start: 31, end: 44, score: 0.85, type: DOMAIN_NAME, star... 0.7, type: PHONE_NUMBER, start: 332, end: 346, score: 0.7, type: EMAIL_ADDRESS, start: 772, end: 794, score: 1.0, ...]

I thought the issue would be only the order.
But if they changed the way the recognizer works, I don't think we can check it.

**Comment by navalev** [comment]
we need to re-evaluate the way we test the iamge analyzer. Let's park this fix for now

**Pull request closed without merging**
