### PR TITLE
Moved py.typed files to proper locations

### PR DESCRIPTION
**Pull request by aivarasbaranauskas**
## Change Description

The original PR #1201 has put the `py.typed` files in wrong directory and they were not packed into the distributed libraries `presidio-analyzer`, `presidio-anonymizer` and `presidio-image-redactor`.

## Issue reference

This PR fixes issue #905

## Checklist

- [x] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [ ] I have signed the CLA (if required)
- [ ] My code includes unit tests
- [ ] All unit tests and lint checks pass locally
- [ ] My PR contains documentation updates / additions if required

### CODE REVIEW

**Comment by aivarasbaranauskas** [comment]
@microsoft-github-policy-service agree

**Review by omri374 — APPROVED** [review]
Thanks!

**Comment by omri374** [comment]
Thanks! We will review and merge this shortly.

**Pull request merged**
