### PR TITLE
Adding Custom recognizers docs (Custom fields)

### PR DESCRIPTION
**Pull request by eladiw**

### CODE REVIEW

**Comment by teochenglim** [comment]
This looks really good. How about spaCy type? Can I inject a custom spaCy NER pipe to recognize something simple such as my company name? or my company product name? Thanks.

**Comment by eladiw** [comment]
> This looks really good. How about spaCy type? Can I inject a custom spaCy NER pipe to recognize something simple such as my company name? or my company product name? Thanks.

Currently we support either new **pattern** based recognizers (regex) or by manually adding new code, into the predefined recognizer directory.
Regarding custom SpaCy entities, this is currently not supported.

**Comment by teochenglim** [comment]
Cool. Thanks for clarifying.

**Comment by omri374** [comment]
Merged with #125

**Pull request closed without merging**
