### PR TITLE
Analysis builder improvements

### PR DESCRIPTION
**Pull request by ebotiab**
## Issue reference

This PR fixes issue #1294 

## Checklist

- [X] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [X] I have signed the CLA (if required)
- [X] My code includes unit tests
- [X] All unit tests and lint checks pass locally
- [X] My PR contains documentation updates / additions if required

### CODE REVIEW

**Comment by omri374** [comment]
Thanks!

**Comment by ebotiab** [comment]
Fixed lint error

**Comment by ebotiab** [comment]
Add other minor fixes of type hints

**Review by Jakob-98 — APPROVED** [review]
Looks good to me, thanks for the improvement! 
Nice work on finding the case where the data in recursive _get_nested_value calls can be None.

**Pull request merged**
