### PR TITLE
Italian fiscal code and driver license recognizers

### PR DESCRIPTION
**Pull request by samirabu**
## Change Description

This contribution adds two recognizers for Italian language:
- Fiscal code: similar to SSN used in United States
- Driver License: number of Italian driver license

For a brief introduction about Italian fiscal code: https://en.wikipedia.org/wiki/Italian_fiscal_code

## Checklist

- [x] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [x] I have signed the CLA
- [x] My code includes unit tests
- [x] All unit tests and lint checks pass locally
- [x] My PR contains documentation updates / additions if required

### CODE REVIEW

**Comment by omri374** [comment]
Thanks for the contribution! 
We'll review the code soon. 
Could you please see if you could sign the CLA? and add the new recognizers to the list of supported entities? https://github.com/microsoft/presidio/blob/main/docs/supported_entities.md

**Comment by samirabu** [comment]
I have signed the CLA and I will add the new recognizers to the list of supported entities in coming hours.

**Comment by samirabu** [comment]
@omri374 I rebased my branch on main and I added the documentation about supported_entities.
Let me know if you need more changes.

**Review by omri374 — APPROVED** [review]
Thanks! Approved

**Review by balteravishay — APPROVED** [review]

**Pull request merged**
