### PR TITLE
fixed minor spelling mistakes

### PR DESCRIPTION
**Pull request by Shail-Shouryya**

### CODE REVIEW

**Comment by omri374** [comment]
Hi @Shail-Shouryya,
Thanks for the PR!
The main work branch is development. Would it be possible to open the PR to point to development instead of master?

**Comment by Shail-Shouryya** [comment]
Hey @omri374,
Missed that branch, just made a PR on develop and should be good to go after the checks! Moving forward I'm assuming that's the branch I should make all PRs to, right?

**Comment by omri374** [comment]
Hey @Shail-Shouryya,
Yes, we use development for day to day commits and master as stable. I saw you opened another PR, but it is also pointing to master. Did you mean to point it to development?

**Comment by Shail-Shouryya** [comment]
Hi @omri374,
Yes, I meant to point the new PR to development but I accidentally pointed it to master again. I fixed it so that it's pointing to development now, and I included the updates from the latest development branch that wasn't in my branch at the time I made the pull request in my second commit. Let me know if there's anything else I could fix!

Closing this PR since I made the changes on the newer PR

**Pull request closed without merging**
