### PR TITLE
Issue 749

### PR DESCRIPTION
**Pull request by rakan41**
## Change Description

Describe your changes

## Issue reference

This PR fixes issue #749

## Checklist

- [X] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [X] I have signed the CLA
- [X] My code includes unit tests
- [X] All unit tests and lint checks pass locally
- [X] My PR contains documentation updates / additions if required

### CODE REVIEW

**Comment by omri374** [comment]
Thanks @rakan41! Looks great.

**Review by omri374 — APPROVED** [review]

**Comment by omri374** [comment]
Failed on linting. Please make sure `flake8` passes successfully.

**Comment by rakan41** [comment]
> 
> 
> Failed on linting. Please make sure `flake8` passes successfully.

Will have a check of this tomorrow and then resubmit!

**Comment by rakan41** [comment]
Passes locally on linting now:
image

**Comment by SharonHart** [comment]
@rakan41 Thanks for your contribution!
I'm not sure that the tests are needed, as this does not add any functionality, just the ability to pass arguments that in-turn add new functionality - correct me if I'm wrong. 
Did you the tests to pass arguments and see that they don't have any affect on the result?
Also, I see that some of the image resources (meant for tests?) are not used. 
Otherwise, this seems good for approval after answering the questions above

**Comment by rakan41** [comment]
> 
> 
> @rakan41 Thanks for your contribution!
> I'm not sure that the tests are needed, as this does not add any functionality, just the ability to pass arguments that in-turn add new functionality - correct me if I'm wrong.
> Did you add the tests to pass arguments and see that they don't have any affect on the result?
> Also, I see that some of the image resources (meant for tests?) are not used.
> Otherwise, this seems good for approval after answering the questions above

Hi @SharonHart , yes that's right. We're just passing kwargs to the redact function. The tests I've included just demonstrate that the kwargs from "analyze" also work in "redact". This done by running redact method 3 times: once without kwargs, once with entities argument, and once with score threshold. It then asserts that the output is different for each run using different parameters. 
I am happy to remove them if you feel that is best. Same goes for the images, I can remove them if not required.  
Let me know your preference.

**Comment by SharonHart** [comment]
@rakan41 I missed the inequality check, the tests makes sense now!
I would leave them, but remove the images as they are not in use

**Comment by rakan41** [comment]
> 
> 
> @rakan41 I missed the inequality check, the tests makes sense now!
> I would leave them, but remove the images as they are not in use

No problem @SharonHart . I've removed the superfluous image files. I've kept "kwargs_test.jpg" as it is used for test mentioned above.

**Review by SharonHart — APPROVED** [review]
Great addition, thanks!

**Pull request merged**
