### PR TITLE
Add ORGANIZATION spacy entity

### PR DESCRIPTION
**Pull request by SharonHart**
## Change Description

Map spacy ORG entity to suppourt ORGANIZATION detection in presidio

## Checklist

- [x] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [x] I have signed the CLA
- [x] My code includes unit tests
- [x] All unit tests and lint checks pass locally
- [x] My PR contains documentation updates / additions if required

### CODE REVIEW

**Comment by SharonHart** [comment]
Spacy does a mediocre job with the organization detection:

image

Not sure we want to add it. @omri374 @navalev your thought?

**Comment by SharonHart** [comment]
with trf model 😲 
image

**Comment by omri374** [comment]
@SharonHart I don't think we want it at this point, but maybe leave it in the code and have it ignored by configuration? is that an option?

**Comment by SharonHart** [comment]
I think that the map converting spacy to presidio entity is easy enough to configure, don't you think? 
I can leave it commented out or document it

**Comment by omri374** [comment]
@SharonHart, yes I would consider to keep the map but remove the ORGANIZATION from the entities (or comment it out)

**Comment by SharonHart** [comment]
@omri374 Done

**Review by navalev — APPROVED** [review]

**Review by omri374 — APPROVED** [review]

**Pull request merged**
