### PR TITLE
feat: Add Bech32 and Bech32m Bitcoin Address Validation in Crypto Recognizer and expand tests

### PR DESCRIPTION
**Pull request by miltonsim**
## Change Description

- Extended the CryptoRecognizer with the capability to validate Bech32 and Bech32m Bitcoin addresses
- Added new test cases have been added to cover Bech32 and Bech32m address validation

## Issue reference

This PR fixes issue #1306 

## Checklist

- [X] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [X] I have signed the CLA (if required)
- [X] My code includes unit tests
- [X] All unit tests and lint checks pass locally
- [X] My PR contains documentation updates / additions if required

### CODE REVIEW

**Comment by omri374** [comment]
Thanks!

**Comment by miltonsim** [comment]
@omri374 thanks for merging my PR! I'm considering whether there might be interest in expanding the CryptoRecognizer to support addresses from cryptocurrencies other than Bitcoin. Would this be a valuable addition?

**Comment by omri374** [comment]
Absolutely

**Comment by miltonsim** [comment]
Cool! I'll look into it soon :)

**Pull request merged**
