### PR TITLE
Use base64 encoded key

### PR DESCRIPTION
**Pull request by zizhong**
## Change Description

This PR enables that the encrypt operator and decrypt operator to use base64 encoded keys.

## Issue reference

This PR fixes issue #1131
## Checklist

- [x] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [x] I have signed the CLA (if required)
- [x] My code includes unit tests
- [x] All unit tests and lint checks pass locally
- [x] My PR contains documentation updates / additions if required

### CODE REVIEW

**Comment by zizhong** [comment]
@microsoft-github-policy-service agree company="Opaque"

**Comment by omri374** [comment]
Thank you @zizhong! Apologies for the delay in responding. We will review this shortly

**Comment by SharonHart** [comment]
@zizhong I haven't seen this PR and already implemented an alternative, what is your take on both? 
https://github.com/microsoft/presidio/pull/1147
I think that yours is also covering the REST API, but also a breaking change?

**Comment by zizhong** [comment]
@SharonHart Thanks! I think your solution is cleaner for a python API. Besides, I have limited cycle working on this so would be great to push your PR and I can close this one.

**Comment by zizhong** [comment]
@omri374 No worries! Since @SharonHart implemented an alternative, I think we can close this one to avoid duplication of efforts.

**Comment by zizhong** [comment]
Closing this in favor of https://github.com/microsoft/presidio/pull/1147

**Pull request closed without merging**
