### PR TITLE
Bugfix in NerModelConfiguration

### PR DESCRIPTION
**Pull request by ebotiab**
## Change Description

Fixing bug #1229

## Checklist

- [x] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [ ] I have signed the CLA (if required)
- [x] My code includes unit tests
- [x] All unit tests and lint checks pass locally
- [x] My PR contains documentation updates / additions if required

### CODE REVIEW

**Review by omri374 — APPROVED** [review]

**Comment by ebotiab** [comment]
@microsoft-github-policy-service agree

**Comment by ebotiab** [comment]
Should I perform any action to the pull request is merged?

**Comment by omri374** [comment]
I will merge it once the CI completes.

**Comment by ebotiab** [comment]
Should I perform any action for the CI to complete?

**Comment by omri374** [comment]
There's a problem with our CI, hence the delay.

**Comment by omri374** [comment]
Thanks! Merged

**Pull request merged**
