### PR TITLE
Updates to the transformers conf docs and yaml file

### PR DESCRIPTION
**Pull request by omri374**
updated the docs for a transformers based pipeline, to make it clearer, and added an example for configuration through code. Based on the discussion in #1463 
Also changed the default config in the docs to match the one in the code.

### CODE REVIEW

**Review by SharonHart — APPROVED** [review]

**Comment by michhar** [comment]
@omri374 Thank you for making these changes.  One question in my mind still is how to find the Hugging Face NER model labels...might be out of scope for the docs here, but perhaps a link or pointer to this could help since it's needed for the configuration file.  Again, thanks for making things clearer.

**Comment by omri374** [comment]
Thanks @michhar. Will directing the user to look into the model's config (e.g. https://huggingface.co/dslim/bert-base-NER-uncased/blob/main/config.json) be the right approach? Not all models explicitly state the classes on their huggingface hub website.

**Comment by omri374** [comment]
Please see #1472

**Pull request merged**
