### PR TITLE
Documentation - Added topic to kafkaConfig, fixed a broken link, and …

### PR DESCRIPTION
**Pull request by ammills01**
…made casing more consistent.

### CODE REVIEW

**Comment by balteravishay** [comment]
Thanks for your contributions! 
does this mean the kafka connector works for you scenario?
adding assignees.

**Comment by balteravishay** [comment]
/azp run

expecting this to only resolve the required reviews since PR only contains .md file changes.

**Comment by LizaShak** [comment]
LGTM

**Comment by balteravishay** [comment]
validated by https://dev.azure.com/csedevil/Presidio/_build/results?buildId=8289

**Comment by ammills01** [comment]
> does this mean the kafka connector works for you scenario?

Nope, still working on that. These were just a few small documentation tweaks I saw were needed while I was trying to understand the project.

**Pull request merged**
