### PR TITLE
Fix range handling in analyzer test util function.

### PR DESCRIPTION
**Pull request by willsthompson**
Add tests verifying correct behavior.

### CODE REVIEW

**Comment by willsthompson** [comment]
Fix for #318.

**Comment by omri374** [comment]
Thanks! Good catch

**Comment by omri374** [comment]
@willsthompson Thank you for your contribution. Your branch is not up to date with Master. Could you please rebase and update your branch?

**Comment by willsthompson** [comment]
@omri374 Sorry, missed that! Should be fixed now.

**Pull request merged**
