### PR TITLE
Fix mkdocs html redirection, setting use_directory_urls

### PR DESCRIPTION
**Pull request by SharonHart**
Set use_directory_urls to false, to allow rest api html redirection 
@navalev Can you push to your fork so that we'll validate it first there?

### CODE REVIEW

**Comment by navalev** [comment]
@SharonHart  my fork is updated as of 2 hours ago. do u want me to use this branch?

**Comment by SharonHart** [comment]
@navalev yes please

**Comment by navalev** [comment]
@SharonHart done

**Comment by navalev** [comment]
what should be the difference?

**Comment by omri374** [comment]
@navalev the redoc swagger doesn't work in all cases

**Comment by navalev** [comment]
still doesnt seem to work in the fork

**Comment by SharonHart** [comment]
@navalev Thanks, will keep investigating. Locally everything works for me

**Review by omri374 — APPROVED** [review]

**Pull request merged**
