### PR TITLE
Addition of leniency parameter in predefined PhoneRecognizer

### PR DESCRIPTION
**Pull request by VMD7**
Addition of `leniency` parameter in predefined `PhoneRecognizer`
## Change Description
-> The `PhoneRecognizer` failed to detect phone numbers when they appeared without any space between text and number, as seen in cases like `testdata630-596-1111`.

-> Internally, the `PhoneRecognizer` utilizes the [phonenumbers](https://github.com/daviddrysdale/python-phonenumbers) library for phone number detection. This library offers a parameter known as `leniency`, which determines the flexibility of the phone number format. The leniency parameter ranges from `0 to 3`, with higher values indicating more strict phone number format match.

-> Initially, the leniency factor in `PhoneRecognizer` was set to `1`, causing it to overlook phone numbers lacking spaces between text and digits. To address this issue, we've enhanced PhoneRecognizer to allow users to adjust the leniency parameter according to their requirements, with a default value of `1`.

-> This enhancement resolves various phone number format issues and empowers users to tailor its behavior to their specific needs.

## Issue reference

This PR fixes issue #1301 

## Checklist

- [x] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [x] I have signed the CLA (if required)
- [x] My code includes unit tests
- [x] All unit tests and lint checks pass locally
- [ ] My PR contains documentation updates / additions if required

### CODE REVIEW

**Review by omri374 — APPROVED** [review]
Thanks!

**Comment by omri374** [comment]
Could be relevant to revisit #772. The phone number recognizer makes some assumptions, such as the regions it looks for phone numbers for (as it is slower to search all of the regions) and other hyperparameters such as leniency.

**Comment by VMD7** [comment]
Yes sure, will go through it.

**Pull request merged**
